import esbuild from "esbuild";
import process from "process";

const banner = `/*
====================================================================
    This file is automatically generated and bundled by esbuild.
    Do not edit this file directly.
====================================================================
*/
`;


const watch = (process.argv[2] === "watch");

const context = await esbuild.context({
    banner: {
        js: banner,
    },
    entryPoints: ["src/main.ts"],
    bundle: true,
    external: [
        "obsidian",
        "electron",
    ],
    format: "cjs",
    target: "es2018",
    treeShaking: true,
    outfile: "main.js",
});

if (watch) {
    await context.watch();
} else {
    await context.rebuild();
    process.exit(0);
}
